export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
}

export enum ActionType {
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
}
